#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Sep 04 22:03:01 CST 2023
# SW Build 3367213 on Tue Oct 19 02:47:39 MDT 2021
#
# IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim hello_world_behav -key {Behavioral:sim_1:Functional:hello_world} -tclbatch hello_world.tcl -view /home/jj/git_repos/fpau_tests/riscv_cores/riscv-steel-core/steel_fpau/hello_world_behav.wcfg -log simulate.log"
xsim hello_world_behav -key {Behavioral:sim_1:Functional:hello_world} -tclbatch hello_world.tcl -view /home/jj/git_repos/fpau_tests/riscv_cores/riscv-steel-core/steel_fpau/hello_world_behav.wcfg -log simulate.log

